# Generated by Django 3.0.2 on 2020-02-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='current_weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
