# Generated by Django 3.0.3 on 2020-02-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0003_auto_20200206_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckmodel',
            name='weight_capacity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
