# Generated by Django 3.0.3 on 2020-02-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0004_auto_20200210_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckmodel',
            name='weight_capacity',
            field=models.FloatField(default=100),
        ),
    ]
