# Generated by Django 3.0.3 on 2020-02-10 14:17

from django.db import migrations, models
import trucks.models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0005_auto_20200210_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckmodel',
            name='weight_capacity',
            field=models.FloatField(default=100, validators=[trucks.models.validate_zero]),
        ),
    ]
